### ISSUE TITLE
tx not sending

### ISSUE THREAD

**Issue by w9drr** [m0iax/JS8CallUtilities_V2#1]
Ubuntu 18.04 64bit.
the app is running, talking to gpsd, and JS8CALL
gets gridsqaure, updates js8call, sends the message to the message field
but doesn't actually send the message. You can manually hit enter or transmit.
Shouldn't it automatically send it tough? maybe missing end of transmission symbol?

**Comment by m0iax** [comment]
Hi W9DRR do you have Autoreply (AUTO) enabled In JS8Call? It wont allow automatic transmit if that is not enabled.

[Image]

 Please check and let me know if that fixes the problem.

73
Mark
M0IAX


Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by w9drr** [comment]
Ah! yes, it had gotten unchecked. That fixed it thanks.
