### ISSUE TITLE
module 'maidenhead' has no attribute 'toMaiden'

### ISSUE THREAD

**Issue by corrt** [m0iax/JS8CallUtilities_V2#10]
I installed on Raspberry Pi, per instructions. running ./JS8CallUtilities.py gives this traceback:
Exception in thread Thread-1:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/JS8CallUtilities_V2/gpsdGPSListener.py", line 114, in run
    grid = mh.toMaiden(lat, lon, precision=self.locator_precision)
AttributeError: module 'maidenhead' has no attribute 'toMaiden'
```
Changing line 114 to 
`    grid = mh.to_maiden(lat, lon, precision=self.locator_precision)`
fixes it, and all works fine.

**Comment by m0iax** [comment]
maidenhead 1.5.0 includes the new method. I have updated all gps options to use this new method and included instructions to existing users to update their maidhenhead to latest

pip install --upgrade maidenhead

Thanks for using JS8Call Utilities.

**Comment by corrt** [comment]
My python is a bit rusty, but you might consider pinning dependency versions to prevent issues like this in the future. Could also allow easier installs (pip installs all dependencies.) I know there are other factors to consider, just mentioning it in case you hadn't considered it.

**Comment by m0iax** [comment]
Your python is clearly superior to mine :-) I had not considered that. I’m making this up as I go. I will look at adding it. Thanks a lot for the suggestion :-)

Regards
Mark
M0IAX
